# Generated by Django 2.2.1 on 2019-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperFile', models.FileField(upload_to='File/')),
                ('PaperName', models.CharField(default=None, max_length=256)),
                ('FirstChecker', models.CharField(max_length=20)),
                ('FirstGrade', models.IntegerField(default=0)),
                ('SecondChecker', models.CharField(max_length=20)),
                ('SecondGrade', models.IntegerField(default=0)),
                ('ThirdChecker', models.CharField(max_length=20)),
                ('ThirdGrade', models.IntegerField(default=0)),
                ('CheckerNumber', models.IntegerField(default=0)),
                ('isUsable', models.BooleanField(default=False)),
                ('FinalGrade', models.IntegerField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
