# Generated by Django 2.2.1 on 2019-06-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0002_auto_20190608_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='PaperChecking',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='papergrade',
            name='PaperName',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
    ]
