# Generated by Django 2.2.1 on 2019-06-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0003_auto_20190616_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='PaperChecking',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
